steps:
# -------------------------------
# Build App 1
# -------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image 1'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image',
    './app1'
  ]

# -------------------------------
# Push App 1
# -------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image 1'
  args: [
    'push',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image'
  ]

# -------------------------------
# Build App 2
# -------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image 2'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image',
    './app2'
  ]

# -------------------------------
# Push App 2
# -------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image 2'
  args: [
    'push',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image'
  ]

# -------------------------------
# Deploy using Cloud Deploy
# -------------------------------
- name: 'google/cloud-sdk:latest'
  id: 'Deploy to GKE via Cloud Deploy'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e

      gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file deploy/dev.yaml --region=us-central1
      gcloud deploy apply --file deploy/prod.yaml --region=us-central1

      gcloud deploy releases create app-release-${SHORT_SHA} \
        --delivery-pipeline=gke-cicd-pipeline \
        --region=us-central1 \
        --from-k8s-manifest=./kubernetes

images:
- 'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image'
- 'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image'

options:
  logging: CLOUD_LOGGING_ONLY
