steps:
# Build App1
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image',
    './gke-cicd/app1'
  ]

# Push App1
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image'
  ]

# Build App2
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image',
    './gke-cicd/app2'
  ]

# Push App2
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image'
  ]

# Deploy
- name: 'google/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e

      gcloud deploy apply --file gke-cicd/deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file gke-cicd/deploy/dev.yaml --region=us-central1
      gcloud deploy apply --file gke-cicd/deploy/prod.yaml --region=us-central1

      gcloud deploy releases create app-release-${SHORT_SHA} \
        --delivery-pipeline=gke-cicd-pipeline \
        --region=us-central1 \
        --source=gke-cicd

images:
- 'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/quickstart-image'
- 'us-central1-docker.pkg.dev/cicd-pipeline-494610/gke-repo/flask-image'

options:
  logging: CLOUD_LOGGING_ONLY
